### ISSUE TITLE
Testes deveriam usar banco de dados próprio ao invés de compartilhar com desenvolvimento

### ISSUE THREAD

**Issue by haggen** [haggen/browserstrategygame#3]
Não tenho certeza se isso funciona, mas minha proposta é:

```python
from . import config

config.database_url = 'sqlite:///test.db'

# Rest of the test...
```

**Comment by douglaslambertinny** [comment]
Por que?

**Comment by haggen** [comment]
Testes automatizado precisam de consistencia. 

Você não pode executar um teste, que envolva o banco de dados, a partir de um estado desconhecido (estado sendo quais dados existem no banco), caso contrário o teste pode passar ou falhar por questões alheias ao que está sendo testado.

Você deve partir sempre de um estado conhecido. Para isso a gente reinicializada o banco antes de cada teste. 

Agora ficaria complicado se cada vez que executássemos os testes nosso banco de desenvolvimento fosse revirado.

Ter essa separação permite o banco de desenvolvimento se manter enquanto eu executo os testes, múltiplas vezes, sem efeitos colaterais.
