### ISSUE TITLE
Trocar SQLModel por SQLAlchemy

### ISSUE THREAD

**Issue by haggen** [haggen/browserstrategygame#4]
SQLModel é basicamente SQLAlchemy+Pydantic numa classe só. A vantagem do Pydantic é a tipagem+validação. Tipagem eu não sei resolver, mas validação é possível no SQLAlchemy. Principalmente, tem muito mais material sobre SQLAlchemy na internet do que SQLModel e há limitações sobre o que o SQLModel consegue fazer, por exemplo: https://github.com/tiangolo/sqlmodel/issues/299

Eu acho que poderíamos manter Pydantic para corpo de requisição/resposta e migrar os modelos de banco tudo pra SQLAlchemy.

O que acha?

**Comment by douglaslambertinny** [comment]
Concordo, perder a capacidade de utilizar o `@hybrid_property` seria uma desvantagem significativa, pois essa funcionalidade é extremamente útil para simplificar consultas. Embora o SQLModel torne algumas tarefas mais práticas, as definições de campos e suas propriedades no SQLAlchemy permanecem bastante consistentes com a experiência do ORM do Alchemy. Então, considerando a importância do `@hybrid_property` e fora outras coisas que ainda não esbarramos, migrar para o SQLAlchemy mantendo o Pydantic para manipulação de dados entre requisições, parece uma escolha **sólida**.

**Comment by haggen** [comment]
Eventualmente a gente poderia revisitar SQLModel. Acredito que a migração seja relativamente fácil dado o grau de compatibilidade com SQLAlchemy.

**Comment by haggen** [comment]
@douglaslambertinny Pensando melhor, acho que podemos postergar essa troca.
